### PR TITLE
GreasedLine changes

### PR DESCRIPTION
**Pull request by RolandCsibrei**
Added AuTO_DIRECTIONS_FACE_TO mode.
Added support for custom UVs.
Fixed simple material shader for non camera facing mode.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14943/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14943/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14943/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14943/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14943/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14943/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14943/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14943/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14943/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14943/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14943/merge/testResults/webgpuplaywright/index.html

**Comment by Popov72** [comment]
You should remove the `package-lock.json` file from your PR.

**Comment by RolandCsibrei** [comment]
> You should remove the `package-lock.json` file from your PR.

Sorry, I didn't even notice it. `git add .` always worked for me until now...
Why is it not included in `.gitignore`?

**Comment by Popov72** [comment]
> Why is it not included in .gitignore?

I think it's because we still commit this file on our side when necessary, but it's not supposed to be done by the end user. @RaananW will know better than me, though.

**Comment by RolandCsibrei** [comment]
> Note that you should not remove the file from the repo, but from your PR only :)

I removed it using the GitHub app on my mobile while I was in the commits section for this PR. I did this for the first time but who in the world could have guessed it will remove it from the repo not from the commits. Sorry :) 


> Also, you shouldn't have any change in your local `package-lock.json` file: have you synchronized your local repo with the main repo?

Yes, all up to date. This is why I always use `git add .` to add all changed files and this is why I was not aware of `package-lock.json` being added.

**Comment by Popov72** [comment]
You should do a `git pull upstream master` to get the `package-lock.json` file back, and commit it in your PR. This should fix it.

**Comment by RolandCsibrei** [comment]
@deltakosh there is a commit https://github.com/BabylonJS/Babylon.js/pull/14934/commits/182fbcb9bc4590f1b07aedc1f13d9591872de900 by you which introduced an error:

```
packages/dev/core/src/Meshes/GreasedLine/greasedLineBaseMesh.ts:246:9 - error TS2322: Type 'FloatArray' is not assignable to type 'number[]'.
  Type 'Float32Array' is missing the following properties from type 'number[]': pop, push, concat, shift, and 5 more.

246         return this._uvs;
 ```

Doesn't count this as a breaking change though? Changing the return type of a public getter? :) I can fix the thing, just don't know what approah you prefer, reverting the commit or I will fix the issue in this PR. Thanks!

**Comment by RolandCsibrei** [comment]
Aaaarqgh :-D
```
[tsl] ERROR in /home/vsts/work/1/s/packages/dev/core/src/Meshes/GreasedLine/greasedLineMesh.ts(180,34)
      TS2802: Type '**Float32Array | number[]**' can only be iterated through when using the '--downlevelIteration' flag or with a '--target' of 'es2015' or higher.
```

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14943/merge/testResults/webgpuplaywright/index.html

**Comment by RolandCsibrei** [comment]
@Popov72  I've managed to fix the `package-lock.json` issue. `git pull upstream master` didn't help, igit always reported all up to date. I had to `git add ./package-lock.json -f`, commit it,  push it and then delete the file on my local copy, `git add .`, commit, push and seems it worked :-)

**Review by RaananW — DISMISSED** [review]
package-lock is being deleted (unless I see a wrong state?)

A git reset, reverting this change and force-push a commit to your branch will probably be the best fix here.

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14943/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14943/merge/testResults/webgpuplaywright/index.html

**Comment by RolandCsibrei** [comment]
@RaananW is it now ok to merge?

**Review by RaananW — APPROVED** [review]

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14943/merge/testResults/webgpuplaywright/index.html
