### ISSUE TITLE
IE11 - multiple definitions of a property not allowed in strict mode

### ISSUE THREAD

**Issue by francisneedham** [BabylonJS/Babylon.js#4257]
# Bugs

- When compiling with babel / webpack in production mode i have this error on IE in console 
"multiple definitions of a property not allowed in strict mode"

- this happened after upgrading from 3.2.0-alpha7 - to current verison

**Comment by deltakosh** [comment]
Can you tell us where this error is? 
We should have try catched it

**Comment by francisneedham** [comment]
Ciao @deltakosh ,
I had the problem on https://v-moda.com/pages/crossfade2-wireless_customizer - now we had to revert to alpha7 because the error was blocking all the website.
I remember that the problem was with the function MultiplyScalar ... the problem was found only in the minified version of babylon because in development mode everything was smooth.

thanks !

Francis

**Comment by deltakosh** [comment]
Woot ! I live your site. Do you want to be highlighted on babylonjs.com?
I'll have  a look on MultiplyScalar to see what is wrong

**Comment by francisneedham** [comment]
@deltakosh  - yes it woul be great :)
the v-moda.com runs on shopify and we have a custom platform entried made on babylon, also for 
speakers  https://v-moda.com/pages/remix_customizer
and in-ear https://v-moda.com/pages/forza_customizer

**Comment by deltakosh** [comment]
Do you mind giving me a title / author and a 800x500 screenshot?

**Comment by deltakosh** [comment]
Also I do not find a MultiplyScalar in Babylon.js so can you point me to where you see it in the code?

**Comment by deltakosh** [comment]
closing issue. Please reopen if required

**Comment by vfabioux** [comment]
Hi,

I had the same issue on Internet Explorer 11, it is caused by Oimo.js, more specifically this file: https://github.com/lo-th/Oimo.js/blob/gh-pages/src/math/Vec3.js where multiplyScalar is defined twice.

You can uninstall Oimo.js if you are not using it.
See http://doc.babylonjs.com/features/npm_support#using-webpack for removing warnings.

**Comment by RaananW** [comment]
I already submitted a PR to oimo regarding this bug, but it is not yet merged - https://github.com/lo-th/Oimo.js/pull/70

**Comment by JinHe-PerkinElmer** [comment]
So, how to resolve this issue? I had the same issue on IE Edge.  in development mode everything is ok but not in production. The error under console is:
SCRIPT1046: Multiple definitions of a property not allowed in strict mode

**Comment by AndrewBogdanovTSS** [comment]
I also have this issue in IE11. Using Vue + Nuxt.js

**Comment by sebavan** [comment]
What version are you using ???

**Comment by AndrewBogdanovTSS** [comment]
I just figured out a cause of my issue - I was accidentally specify some of my components props twice, such as
```
<w-button btn-style="orange" btn-style="red"/>
```
Once that code was converted into js object - it was causing an issue with multiple definitions
