### PR TITLE
NullEngine: avoid super in supportsUniformBuffers accessor (fix no-super-in-accessor lint)

### PR DESCRIPTION
**Pull request by bkaradzic-microsoft**
## What

Fixes the `babylonjs/no-super-in-accessor` lint error that is currently **red on `master`**:

```
packages/dev/core/src/Engines/nullEngine.pure.ts(125,52): error babylonjs/no-super-in-accessor:
super.supportsUniformBuffers inside a get/set accessor mis-compiles to `undefined` in the UMD build
```

The `NullEngine.supportsUniformBuffers` getter read `super.supportsUniformBuffers`. `super` inside a decorated accessor downlevels to `undefined` in the ES5 UMD bundle (it works in dev/ESM), which is exactly what the `no-super-in-accessor` rule guards against.

## Fix

Inline the base `ThinEngine` getter expression (`this.webGLVersion > 1 && !this.disableUniformBuffers`) instead of calling `super.supportsUniformBuffers`. Behavior is identical — it reads the same live properties the base getter reads — and it no longer uses `super` inside the accessor. (`super` in a normal method/constructor is fine; only accessors are affected.)

```ts
public override get supportsUniformBuffers(): boolean {
    return !!this._options?.enableMultiview || (this.webGLVersion > 1 && !this.disableUniformBuffers);
}
```

## How this reached `master` (root cause)

This is a **semantic merge skew** between two PRs that were open at the same time — neither PR's CI ever tested the combination:

| When (UTC) | Event |
|---|---|
| 2026-06-15 20:44 | **#18580** "Fix camera frozen in UMD build" merges — it **adds** the `no-super-in-accessor` rule (and fixes the then-existing violations, e.g. `TargetCamera`). |
| 2026-06-15 20:53–21:02 | **#18576** "Add NullEngine multiview render-state testability" runs its `Format, Lint, and more` check and **passes** ✅ — but its merge base **does not contain #18580's rule** (the two branches were diverged). So its lint ran *without* the new rule. |
| 2026-06-16 08:00 | **#18576** merges on that green-but-stale CI, introducing the `super.supportsUniformBuffers` getter. |
| now | `master` = rule (#18580) **+** violation (#18576) → lint **red**. |

Because the repo doesn't require a PR branch to be up to date with the absolute-latest `master` before merging, #18576 merged against a base snapshot that predated #18580. Re-running #18576 against post-#18580 `master` (e.g. `Update branch` / rebase) would have caught this before merge.

## Verification

- One-line behavior-preserving change; `super` removed from the accessor, so `no-super-in-accessor` no longer triggers.
- Unblocks `master` and every open PR currently inheriting this repo-wide lint failure.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by deltakosh — APPROVED** [review]

**Comment by sebavan** [comment]
Closed as https://github.com/BabylonJS/Babylon.js/pull/18585 landed with the same fix

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/18587/merge

Test environment:
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/18587/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/18587/merge/index.html#WGZLGJ#4600

Links to test your changes to core in the published versions of the Babylon tools (does not contain changes you made to the tools themselves):

https://playground.babylonjs.com/?snapshot=refs/pull/18587/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/18587/merge
https://gui.babylonjs.com/?snapshot=refs/pull/18587/merge
https://nme.babylonjs.com/?snapshot=refs/pull/18587/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/18587/merge#BCU1XR#0

*If you made changes to the sandbox or playground in this PR, additional comments will be generated soon containing links to the dev versions of those tools.*

**Comment by bjsplat** [comment]
Interaction tests

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/18587/merge/testResults/interactionplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/18587/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/18587/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
## 🟢 Memory Leak Test Results

**13** passed, **0** leaked out of **13** scenarios

🟢 All memory leak tests passed — no leaks detected.

<details>
<summary>Passed Scenarios (13)</summary>

| Scenario | Package |
|----------|---------|
| Core Feature Stack | @babylonjs/core |
| Core Rendering Materials Shadows Stack | @babylonjs/core |
| Core Textures Render Targets PostProcess Stack | @babylonjs/core |
| GUI Fullscreen UI Controls | @babylonjs/gui |
| GUI Mesh ADT Controls | @babylonjs/gui |
| Loaders Boombox Import | @babylonjs/loaders |
| Loaders OBJ Direct Load | @babylonjs/loaders |
| Loaders STL Direct Load | @babylonjs/loaders |
| Materials Library Stack | @babylonjs/materials |
| Serializers glTF Export | @babylonjs/serializers |
| Serializers GLB Export | @babylonjs/serializers |
| PostProcesses Digital Rain Stack | @babylonjs/post-processes |
| Procedural Textures Stack | @babylonjs/procedural-textures |

</details>

**Comment by bjsplat** [comment]
## ⚡ Performance Test Results

🟢 All performance tests passed — no regressions detected.
