### ISSUE TITLE
TypeScript compile fails with Typescript 3.1

### ISSUE THREAD

**Issue by CynicalBusiness** [BabylonJS/Babylon.js#5277]
- **Bug repro on [playground](https://playground.babylonjs.com)**: N/A
- **Expected result**: Typescript project using BabylonJS compiles with TS 3.1
- **Current result**: Typescript project using BabylonJS does NOT compile with TS 3.1

TypeScript 3.1 released recently and, during some changes to a project of mine, I updated my dep from `3.0.1` to `3.1.1`. Almost immediately, however, builds began to fail.

This message keeps getting written to console:
```
Using tsc v3.1.1
node_modules/babylonjs/babylon.d.ts(250,5): error TS2687: All declarations of 'fullscreen' must have identical modifiers.
node_modules/babylonjs/babylon.d.ts(293,5): error TS2687: All declarations of 'orientation' must have identical modifiers.
node_modules/babylonjs/babylon.d.ts(293,5): error TS2717: Subsequent property declarations must have the same type.  Property 'orientation' must be of type 'ScreenOrienta
tion', but here has type 'string'.
node_modules/typescript/lib/lib.dom.d.ts(4030,14): error TS2687: All declarations of 'fullscreen' must have identical modifiers.
node_modules/typescript/lib/lib.dom.d.ts(13881,14): error TS2687: All declarations of 'orientation' must have identical modifiers.
```

I've tried this with both `3.3.0-beta.2` and `3.3.0-rc.4` of BabylonJS. This issue does not happen when I roll back to TSC v3.0.

I *suspect* it has something to do with [these breaking changes](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#some-vendor-specific-types-are-removed-from-libdts), just judging by the output, but I don't know for certain.

**Comment by deltakosh** [comment]
I did the change but unfortunately typedoc does not yet support it. 
So we have to wait for them first

Could you try to fix the discrepancies perhaps? (That could be as simple as fixing orientation and fullscreen declarations in the mixin file)

**Comment by CynicalBusiness** [comment]
Actually, scratch that:

Not only does Babylon have that lib, but something I touched in my local copy caused that symbol to no longer be available either.

I have the other errors fixed, but that third error remains.

**Comment by deltakosh** [comment]
Well yeah that's a mess. You may need to stay with TS 3.0.1 for a bit of time

**Comment by deltakosh** [comment]
Should be good now
Please let me know if you can test it

**Comment by CynicalBusiness** [comment]
I tried to test it. `master` fails with `npm`/`yarn`, so I tried to copy the files from master into my working directory, but it does not remove the error. It appears `dist/preview release/babylon.d.ts` is completely unchanged from my local copy.

I tried to build from TS source myself, but `gulp` is failing because apparently `gulpInst.start` is `undefined`. .-.

**Comment by deltakosh** [comment]
can you try from dist/preview release?

**Comment by CynicalBusiness** [comment]
I cloned a fresh copy down from the current master, and updated my local copy with that.
The error does appear to be resolved with TypeScript `v3.1.1` and 090a72b.

(My project actually builds now, yay! Some other lib needed 3.1.1 to function)

**Comment by maxime1992** [comment]
I'm currently using Typescript `3.1.3` and I've got the following errors:

```
node_modules/babylonjs/babylon.d.ts(252,5): error TS2687: All declarations of 'fullscreen' must have identical modifiers.
node_modules/babylonjs/babylon.d.ts(303,14): error TS2717: Subsequent property declarations must have the same type.  Property 'orientation' must be of type 'ScreenOrientation', but here has type 'string'.

Error: node_modules/babylonjs/babylon.d.ts(252,5): error TS2687: All declarations of 'fullscreen' must have identical modifiers.
node_modules/babylonjs/babylon.d.ts(303,14): error TS2717: Subsequent property declarations must have the same type.  Property 'orientation' must be of type 'ScreenOrientation', but here has type 'string'.
```

Any solution?

**Comment by deltakosh** [comment]
Are you using bjs 4.0? This should fix the problem

**Comment by CynicalBusiness** [comment]
You have to specifically ask for the working version from NPM, most likely. At current, if you just grab "latest", you get `3.3.0`, which does not work with TS 3.1

Try `npm i -S babylonjs@4.4.0-alpha.4` (or `yarn add babylonjs@4.4.0-alpha.4`), as this is the latest on NPM at this time.

**Comment by sancelot** [comment]
@CynicalBusiness :   `npm i -S babylonjs@4.0.0-alpha.4 `je pense ?

**Comment by istudiodigital** [comment]
Hi,

I'm currently using Typescript 3.3.4 and BabylonJS 3.3 and I'm having the same issue.

It seems it's been a while for now, has there been a solution yet?

![Screenshot_032719_075832_PM](https://user-images.githubusercontent.com/41804823/55104485-b4e47e00-50ca-11e9-8c85-cbcd81d8f879.jpg)

**Comment by CynicalBusiness** [comment]
@istudiodigital 
Bump your BabylonJS version up to `babylonjs@preview` (or `babylonjs@4.0.0-beta.3`, which is the current preview) and it should work with TS 3.3.

Be careful though, TS 3.4 is rolling another large batch of breaking changes, so we'll see how that turns out. Probably hold back on that if you can.

**Comment by istudiodigital** [comment]
@CynicalBusiness 
Thanks for the hint, I've tried it and now I get this:
`Assets/Babylon/Library/babylon.d.ts(4439,18): error TS2567: Enum declarations can only merge with namespace or other enum declarations.
Assets/Babylon/Library/babylon.manager.d.ts(970,10): error TS2567: Enum declarations can only merge with namespace or other enum declarations.
`

**Comment by CynicalBusiness** [comment]
That looks like BabylonJS and Scene Manager not working together. My guess is you'll need to bump Scene Manager (Now called Unity Exporter?) as well.

**Comment by istudiodigital** [comment]
Yes, that worked!

Thanks again!

**Comment by seraekim** [comment]
@istudiodigital 

Hello, excuse me. I am a newbie to babylonjs.

I tried 
npm i -g babylonjs@preview
npm i -g typescript@3.3

but still unity console shows "error TS2567: Enum declarations can only...."
I don't know how to apply your way.
Can you help me?

**Comment by deltakosh** [comment]
Pinging @MackeyK24

**Comment by MackeyK24** [comment]
I found issue... Let me rebuild with latest typescript and babylon 4.0.0 rc

**Comment by seraekim** [comment]
@MackeyK24 
Oh thank you, 
I am waiting for its renewal version of 
https://github.com/BabylonJS/UnityExporter/blob/master/Archive/Babylon%20Editor%20Toolkit%202019-04.unitypackage

**Comment by MackeyK24** [comment]
FYI... the archive folder is for **OLDER** versions. The date in the filename is the date i moved it to archive folder... That version is NOT the official 2019 build of toolkit.

The 2019 version compatible builds are at: https://github.com/BabylonJS/UnityExporter/tree/master/Redist

I will update that build as soon i get the FIX from @bghgary  about the Bone Matrix for skeletons, plus a couple other mesh fixes like: Tangents and Vertex Colors for the meshes and a MUCH better ALPHA/TRANSPARENCY Export (Not as good as the new upcoming version... but a stop gap until i get the new version ready)
