### PR TITLE
fix: restore setTextureFormatToUse on WebGPU/Native engines

### PR DESCRIPTION
**Pull request by Popov72**
## Summary

Moves the `setTextureFormatToUse` / `setCompressedTextureExclusions` / `texturesSupported` / `textureFormatInUse` prototype augmentations from `Engine` (WebGL-only) up to `AbstractEngine`, so they are available on every engine (WebGL, WebGPU, Native).

## Why

These methods have been silently broken on WebGPU since PR #14931 (April 2024 — "Remove WebGPUEngine dependency on Engine"). Before that change `WebGPUEngine extends Engine`, so it inherited the augmentation in `engine.textureSelector.ts`. After #14931 `WebGPUEngine` extends `AbstractEngine` (now `ThinWebGPUEngine`), and the methods were no longer reachable — calling `engine.setTextureFormatToUse(...)` on a WebGPU engine throws `TypeError: ... is not a function`.

The underlying hook `_transformTextureUrl` already lives on `AbstractEngine` and is honored by `AbstractEngine.createTexture` / `createCubeTexture`, so the mechanism itself works; only the public entry point was missing.

WebGPU already exposes the required caps (`_caps.astc`, `_caps.s3tc`, `_caps.etc2`), so moving the augmentation to `AbstractEngine` is sufficient — no WebGPU-specific logic is needed.

## Changes

- New `packages/dev/core/src/Engines/AbstractEngine/abstractEngine.textureSelector.ts` — augments `AbstractEngine` with `setTextureFormatToUse`, `setCompressedTextureExclusions`, `texturesSupported`, `textureFormatInUse`, `_textureFormatInUse`, `_excludedCompressedTextures`. Replaced `Function.bind` with an arrow closure per repo conventions.
- `packages/dev/core/src/Engines/AbstractEngine/index.ts` — registers the new file (using the "must import first since nothing references the exports" pattern, same as the previous file).
- `packages/dev/core/src/Engines/Extensions/engine.textureSelector.ts` — reduced to a thin re-export of the new location. Existing side-effect imports (e.g. `import "core/Engines/Extensions/engine.textureSelector"`) keep working, and the method becomes reachable on all engine implementations.

## Back-compat

- No public API change. All methods keep the same signatures.
- `Engine` instances still resolve the methods, via inheritance from `AbstractEngine`.
- Existing side-effect imports of the old file path continue to wire up the prototype correctly.

## Risk

Low. The augmentation is now on the shared base class; the implementation is unchanged aside from the `bind` → arrow replacement. Typecheck/lint over `packages/dev` report no new errors.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/18347/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/18347/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/18347/merge/index.html#WGZLGJ#4600

Links to test your changes to core in the published versions of the Babylon tools (does not contain changes you made to the tools themselves):

https://playground.babylonjs.com/?snapshot=refs/pull/18347/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/18347/merge
https://gui.babylonjs.com/?snapshot=refs/pull/18347/merge
https://nme.babylonjs.com/?snapshot=refs/pull/18347/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/18347/merge#BCU1XR#0

*If you made changes to the sandbox or playground in this PR, additional comments will be generated soon containing links to the dev versions of those tools.*

**Review by deltakosh — APPROVED** [review]

**Comment by bjsplat** [comment]
Interaction tests

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/18347/merge/testResults/interactionplaywright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/18347/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/18347/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Interaction tests

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/18347/merge/testResults/interactionplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/18347/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/18347/merge/testResults/webgpuplaywright/index.html
