### PR TITLE
Allow single comment syntax in #if constructs in shader code

### PR DESCRIPTION
**Pull request by Popov72**
See https://forum.babylonjs.com/t/shader-defines-and-comments/10700

I have also moved the "fake soft transparent shadows" entry of the what's new file to the "Major udpates" section as requested by @deltakosh (forgot to do it earlier).

### CODE REVIEW

**Comment by Popov72** [comment]
Lot of build steps failing because of https://github.com/BabylonJS/Babylon.js/pull/8095 it seems:
* lint: Failed to lint: /home/vsts/work/1/s/src/Probes/reflectionProbe.ts [96, 1]: trailing whitespace.
* "typescript all":
  * Materials/Textures/Filtering/hdrFiltering.ts(45,12): error TS2322: Type 'undefined' is not assignable to type 'number'.
  * Materials/Textures/baseTexture.ts(363,13): error TS2322: Type 'undefined' is not assignable to type 'number'.
  * Materials/Textures/Filtering/hdrFiltering.ts(45,12): error TS2322: Type 'undefined' is not assignable to type 'number'.
  * Materials/Textures/baseTexture.ts(363,13): error TS2322: Type 'undefined' is not assignable to type 'number'.

**Comment by sebavan** [comment]
yup all good on my branch going in real soon :-)

**Comment by sebavan** [comment]
I merged it in, you can try to update on your side :-) I ll monitor the build in the mean time. Github checks were green as the only check the first 2 tasks... I definitely need to find why this happens as it is pretty scary, I have been spending my evening recovering from my merge to master which I should have seen really early.
