### PR TITLE
fix Blender export

### PR DESCRIPTION
**Pull request by rkusa**
I got the following Blender export error:

```
========= An error was encountered =========
  File "/Applications/blender.app/Contents/Resources/2.73/scripts/addons/io_export_babylon.py", line 268, in execute
    self.shadowGenerators.append(ShadowGenerator(object, self.meshesAndNodes, scene))
  File "/Applications/blender.app/Contents/Resources/2.73/scripts/addons/io_export_babylon.py", line 1206, in __init__
    for mesh in meshesAndNodes:
ERROR:  'Node' object has no attribute 'castShadows'
========= end of processing =========
```

This PR fixes this issue (seems to be introduced in 6628dc3b6644c295456fe3b4edf9fb032f78421f) by adding the `castShadows` attribute to the `Node` class.

### CODE REVIEW

**Comment by Palmer-JC** [comment]
Could you also update line 4 with version 1.6.2, then resubmit?

**Comment by rkusa** [comment]
Sure, done
